### ISSUE TITLE
[OSWeb] Send API requests through CloudFront

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#127]
### Description
Change the OSWeb FE to make its API requests using relative URLs so that requests route through CloudFront so that responses are cached and so that we don’t have CORS problems.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.pob136gjkgvu

For Unified Reading Experience

### Problem Description
The OSWeb FE currently makes API requests using absolute URLs. Once OSWeb moves behind CloudFront, this will no longer work in all environments. This PR changes the apiOrigin from something like “https://openstax.org” to an empty string, so that API requests use relative URLs.

### Notes
- Deployment PR: https://github.com/openstax/oscms-deployment/pull/76
- The apiOrigin is passed into the `Share` component as the `pageUrl` and then used on this line: https://github.com/openstax/os-webview/blob/a4dd1584881ac7f700a90fdd76e8f3309c373770/src/app/components/share/share.js#L26 - need to make sure this line is ok with `pageUrl` being an empty string.
- Timing: Significantly before Rex release so we can test OSWeb behind CloudFront
- Blocks:
  - CloudFront/OSWeb cache invalidation story

### Acceptance Criteria
- On a random series of OSWeb pages (the more the merrier), a tester can see in the QA console that all requests that go to an openstax.org subdomain go through the CloudFormation domain, not through the direct OSWeb domain.

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by jpslav** [comment]
@mwharrison @RoyEJohnson is this effectively done? (api requests are relative requests so will go through openstax.org which will become the CloudFront distribution)

**Comment by RoyEJohnson** [comment]
This is done.
