### ISSUE TITLE
[OSWeb] Set cache headers on responses

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#131]
# Description
Set cache headers on responses so that content is cached within CloudFront for an appropriate amount of time.
Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.gnwzduz31dkx

For Unified Reading Experience

# Problem Description
CloudFront decides how long to cache content based on settings within the distribution and headers returned from the OSWeb origin (insert link here).  Need to make sure that we’re setting headers on responses that indicate how long to cache objects in CloudFront.

# Notes
- Timing: Nice to have at least thought through this prior to the Rex release, but isn’t required; if we set cache durations in the distribution and have the cache invalidation story complete, we can get by without this.  
- Blocks:
   - Nothing

# Acceptance Criteria
- Spot check that headers are set on responses.  
- Write tests to verify that cache headers are set
- An immediate reload should probably show a cache hit from CloudFront for the resources that are anticipated (can’t control what CloudFront caches

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [x] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [x] If an issue is included in a product phase, then Release is selected.

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
Completed.

**Comment by kathi-fletcher** [comment]
What is an appropriate length of time? that is a fuzzy criteria. Testing that their is a header inserted doesn't tell whether it is the right thing
