### ISSUE TITLE
[Accounts] Alias all routes under /accounts

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#135]
### Description
For clients that access the Accounts API via the CloudFront distribution, provide an alias so that endpoints like /api/v1/something can be accessed via /accounts/api/v1/something, so that access via the 

**update** also do this for non-API routes and assets

For Unified Reading Experience.

### Notes
- Don’t need to change any frontend code; this just makes the accessing the API (and pages) via the distribution possible.
- Timing: Before Rex release
- Blocks: Nothing.

### Acceptance Criteria
- Spot check proof that endpoints (and assets/pages) can be accessed with an /accounts prefix
- write specs (should be possible?) to test that requests to /accounts/blah make it to the right place.
- spec that checks that no Accounts routes start with `accounts/` 

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by jpslav** [comment]
At first I thought we may be able to do this in the `config/routes.rb` file, but that approach may add too much overhead re duplicating all routes to have a cousin with an `/accounts/` prefix, and would make a call to `rake routes` pretty messy.  

A second idea is to write a small bit of Rack middleware to intercept incoming requests and remove the `accounts/` prefix if it is there.  This page has an example that looks similar to what we want: http://andywenk.github.io/rails/2014/06/11/rack-middleware-in-rails-to-recode-the-url

If this works, try to write some specs (request specs, maybe a feature spec?) to test that the prefix works.

**Comment by Malar-Natarajan** [comment]
Just regression testing

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Malar-Natarajan** [comment]
https://github.com/openstax/accounts/pull/657
https://github.com/openstax/accounts/pull/654

**Comment by Brooke-Fail** [comment]
Verified in Production.

**Comment by Malar-Natarajan** [comment]
verify https://accounts-qa.openstax.org/api/user is same as https://accounts-qa.openstax.org/accounts/api/user

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.

**Comment by Brooke-Fail** [comment]
Passed second round of testing on Staging.
