### ISSUE TITLE
Change Request: Enable cache (Redis) data compression for Accounts

### ISSUE THREAD

**Issue by jessicatelles** [openstax/business-intel#147]
@jessicatelles commented on [Tue Oct 23 2018](https://github.com/openstax/bit-backlog/issues/13)

Trello: https://trello.com/c/xzwgsjtN/783-change-request-enable-cache-redis-data-compression-for-accounts

Summary
--
Rails cache compression is disabled by default in our current version. This commit rails/rails: ed10016 enables it globally by default for Rails 5.2+. We should probably do the same. Accounts mostly uses Redis for settings (tiny) and background job data (huge).

Current Behavior
--
Data is stored in Redis uncompressed.

Desired Behavior
--
Compress the data before storing it in Redis.

---

@jessicatelles commented on [Tue Oct 23 2018](https://github.com/openstax/bit-backlog/issues/13#issuecomment-432280040)

Dante:
Jun 15: @allisonhowell I looked and couldn't find code for this in accounts. I don't think this card is done. Only exercises was done at the time.

Allison:
Jun 15: @Dantemss Ed mentioned in scrum that this work is complete. Can I archive this card?

Bruce:
May 3: Allison will discuss priority with Ed.

Checklist for Done
--

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by Brooke-Fail** [comment]
Talked to Bryan, there isn't a way for me to verify this so I am closing at complete.
