### ISSUE TITLE
Implement Google PageSpeed recommendations for openstax.org

### ISSUE THREAD

**Issue by jessicatelles** [openstax/business-intel#165]
@jessicatelles commented on [Tue Oct 23 2018](https://github.com/openstax/bit-backlog/issues/10)

Trello: https://trello.com/c/HXHS8Np9/886-implement-google-pagespeed-recommendations-for-openstaxorg

Description
--
There are a number of recommendations at https://developers.google.com/speed/pagespeed/insights/?url=openstax.org&tab=desktop
for improving the performance (and user experience) at openstax.org.

Some recommendations are not workable with our current technology choices (for example, The entire HTML response was not sufficient to render the above-the-fold content. because we have a single-page app that loads content from the CMS.) We should consider them when we are designing the platform for Unicorn. Some server-side rendering might make sense.

Other recommendations can be implemented, possibly with devops help.

Acceptance
-- 

Impact
--
Severity: [ ] High [ ] Medium [ ] Low

https://github.com/openstax/oscms-deployment/pull/66
https://trello.com/c/h9d3d4lt/158-enable-automatic-object-compression-in-aws-cloudfront
https://trello.com/c/eEl9uQYw/408-seo-improve-page-load-times

Tasks
--
- [ ] Enable compression of CMS data (in particular the books query)

---

@jessicatelles commented on [Tue Oct 23 2018](https://github.com/openstax/bit-backlog/issues/10#issuecomment-432270573)

Dante:
Aug 9: I was working on parts of this in relation to SEO: Improve Page Load Times
I submitted the following PR: openstax/oscms-deployment: Pull Request 66
I also submitted the following change request to the devops board: Enable automatic object compression in AWS CloudFront

Checklist for Done
--

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by allisonhowell** [comment]
@RoyEJohnson This is really interesting and definitely impacting our SEO with Google's "mobile first" philosophy: https://developers.google.com/speed/pagespeed/insights/?url=Openstax.org&tab=mobile

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production
