### ISSUE TITLE
allow customizing the "view online" book link

### ISSUE THREAD

**Issue by TomWoodward** [openstax/business-intel#186]
# Description 

Allow specifying arbitrary relative url for the "view online" link in the book details sidebar, so that the books detail page can reference the unified reading experience. 

Acceptance: 
- The book details page for a given book can point to the unified reading experience for that book, so that we can take users to that book _once it is made available in REX_. 
- Because we will not launch all books in REX simultaneously, and because some books will remain in CNX for TBD period, we must support the case in which "view online" can point to either a book in CNX or a REX book.
- When a user clicks "view online" and that link references REX, the user is taken to REX in the same browser tab. 
- Verify the existing behavior is upheld for CNX books -- when a user clicks "view online" and that link references CNX, that user is taken to CNX in a new browser tab.
- Verify that Google Analytics continues to track the REX "view online" links as a measurable event. 

### Unit Tests
TBD but we want to add as a task that the Unified team will participate in testing this card. 

### Integration Tests
TBD but here are some we've documented so far... 

- verify the link in the book details page opens the book viewer in the same browser tab
- verify the 'Loading...' status is easily detectable via selenium as well as when the JS is done loading & ready to accept input (for additional selenium tests)

# Impact
* *Severity*: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurence**: [ ] High [ ] Medium  [ ] Low

# Acceptance

# Next Steps for User
_If this story is accepted or rejected, what does user need to know now?_

# Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by kjdav** [comment]
@allisonhowell This is a new card for BIT/Unified that does not need to be done this quarter. We are adding it to this list so we can track it and remember it for future team planning.

**Comment by berkalpyakici** [comment]
@TomWoodward Feature is added. If `WEBVIEW REX LINK` is set, `View Online` button will take clients to REX webpage instead of CNX.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
