### ISSUE TITLE
Implement CloudFront cookie forwarding

### ISSUE THREAD

**Issue by kjdav** [openstax/business-intel#199]
# Description 
Enumerate the cookies that CloudFront should forward to OSWeb, and say which cookies impact the content that is returned, so that CloudFront can cache content effectively and correctly.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.8yzc1ndrvmnp

Problem Description
CloudFront can be configured to cache based on cookies forwarded from clients to the origin.  When we know what OSWeb needs and how those cookies impact what is returned by archive, we can configure CloudFront to behave correctly.

Notes
E.g. will at least want the SSO cookie and the OSWeb cookie; these cookies may impact some endpoints/routes and not others.
CloudFront: Caching Content Based on Cookies
Timing: No later than Jan 2019
Blocks:
Nothing

# Acceptance Criteria
Unified team gets a list of cookies need to be forwarded

# Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by kathi-fletcher** [comment]
@kjdav How do you know whether a cookie needs to be forwarded? How will you know that you have the correct list of cookies (what behaviors will be true that QA can test?) [Some dev can answer]

**Comment by jpslav** [comment]
Any cookie that osweb uses needs to be forwarded.  This will at least be the Accounts SSO cookie.  So we just need the list from osweb about which cookies they use.  We can then tell Cloudfront to forward those to osweb and CloudFront can still give us some caching benefit.  

If we tell Cloudfront to forward all cookies things will definitely work, but then CloudFront won't do any caching (b/c there isn't any content that can be shared between different users because CloudFront would keep separate caches for unique cookie values)
