### ISSUE TITLE
BE: Implement CloudFront cookie forwarding

### ISSUE THREAD

**Issue by laurenloh** [openstax/business-intel#213]
### Description
Enumerate the cookies that CloudFront should forward to OSWeb, and say which cookies impact the content that is returned, so that CloudFront can cache content effectively and correctly.

Story: https://docs.google.com/document/d/1UrhAptBawdqpQYyf7K6eHV6W-B7Pr22o9tNJxXld11w/edit#heading=h.8yzc1ndrvmnp

### Acceptance Criteria
- A list of the cookies that CloudFront should forward to OSWeb
- Noted which cookies impact the content that is returned

### Checklist for Done
- 2-DDD
  - [x] Description is complete 
  - [x] Acceptance Criteria is complete
  - [x] Test criterias are defined
  - [x] Estimate is updated
  ~~- [ ] If the issue is a story, then Epic is selected~~
  ~~- [ ] If the issue is included in the quarterly plan, then Milestone is selected~~
  ~~- [ ] If the issue is included in a product phase, then Release is selected~~
- 2B-UX DESIGN
  ~~- [ ] The UX design is complete and the design files are attached to the issue~~
  ~~- [ ] The UX design is approved by the Product Manager~~
  ~~- [ ] The test plan is drafted.~~
- 3-CODE
  ~~- [ ] The code change meets the acceptance criteria (for a story or change request), or fixes the identified defect (for a bug)~~
  ~~- [ ] Affected areas in the code are identified~~
  ~~- [ ] The code change is merged to master (dev review done, test suite passed, code coverage maintained)~~
- 3A-NOT CODE
  - [ ] The work is completed and meets the acceptance criteria for the issue
- 4A-UX REVIEW
  - [ ] The implemented feature is accepted by the UX Designer and the Product Manager
  - [ ] The test plan is finalized
- 5A-FUNCT VER
  - [ ] All tests in test plan passed
- 5C-REGRESSION
  - [ ] Affected areas that were identified are passed

- **QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

- **Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by mwharrison** [comment]
@jpslav - the only cookie that we have being passed around `ox`. We'd like to call this done and say this is our "list of cookies" - do you need anything else?

**Comment by jpslav** [comment]
Thanks, this is fine.  We are now forwarding all cookies to osweb for the
home page.
https://github.com/openstax/unified-deployment/blob/master/cfn/cloudfront/main_distribution.yml#L212
and
API calls
https://github.com/openstax/unified-deployment/blob/master/cfn/cloudfront/main_distribution.yml#L286
but
not forwarding cookies for the assets
https://github.com/openstax/unified-deployment/blob/master/cfn/cloudfront/main_distribution.yml#L236
