### ISSUE TITLE
Few words being hidden by rover image in the last section for almost all mobile devices

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/business-intel#256]
### Description
Few words being hidden by rover image in the last section for almost all mobile devices

**SCENARIO** _Briefly describe the issue._
Few words being hidden by rover image in the last section for almost all mobile devices
----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [X] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
![Screen Shot 2019-02-08 at 1.52.50 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/d03fdaba-5317-4d53-b4d2-e7c6649b7647)

![Screen Shot 2019-02-08 at 1.52.19 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/54f4461e-7f45-4fd8-b13d-cd8bd0b87369)

![Screen Shot 2019-02-08 at 1.46.24 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/00cbb230-2273-4fb8-b2c9-34e0c0ff7a09)

-----------------
### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by RoyEJohnson** [comment]
I'm not able to connect the PR via Zenhub, so it's here:
https://github.com/openstax/os-webview/pull/1336

**Comment by RoyEJohnson** [comment]
In tablet size,
```.text-block .cards .text-block {
    padding-right: calc(30vw - 7rem);
}
```

**Comment by Brooke-Fail** [comment]
If there are no additional UX changes, this has been verified in QA.

**Comment by victoria-cooke** [comment]
@Brooke-Fail Just took a look; I have no additional UX changes.

**Comment by ejp3** [comment]
Verified in Production
