### ISSUE TITLE
Adjust cards on "Meet Rover" section of Rover page to form an even grid 

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#262]
# Description
The "Meet Rover" section of the Rover page was designed to hold six cards, however, we may be adjusting cards based on features and other factors. We need to have the grid automatically adjust when cards are taken away so that it appears even. 

# Acceptance Criteria
- Four cards on the "Meet Rover" section of the page are stacked "two over two."
- Six cards are "three over three"

We won't be adding odd numbers or adding more than six, so those are the only two scenarios I anticipate. 

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: 
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by allisonhowell** [comment]
![Screen Shot 2019-02-13 at 10.53.27 AM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/54a12464-4fc8-42c9-932b-bc739a7cf005)

**Comment by allisonhowell** [comment]
@RoyEJohnson David asked us to change the copy so we went from six cards to four.

**Comment by victoria-cooke** [comment]
@allisonhowell If we're able to get all the cards in a row at four without too much warping, that solution is ideal. However, if there's too much text for this to be reasonable, the stacked option works. The stacked option is good for six.

**Comment by Malar-Natarajan** [comment]
@RoyEJohnson 

the mobile versions of this change looks like this screenshot. In most cases, the cards are too long to fit the screen and requires scrolling to view the full card. Also please watch the videos for different chrome & safari mobile displays when I change the grid from 2*2 and 3*2. There are no scrollbars to see the 3rd & 6th card and if I do a hand swipe, the cards looks like floating without any background

![Screen Shot 2019-04-02 at 1.13.47 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/eb7597cb-eca3-4cce-ac5b-d2e9c572d982)

https://drive.google.com/file/d/1NpZWCg1Hl4u137jXGTZJnTsj8_azYsMg/view?usp=sharing

https://drive.google.com/file/d/1tmvG5u3zJEyxt3ruWOqztAnYwjLwhFLo/view?usp=sharing

**Comment by Malar-Natarajan** [comment]
@victoria-cooke 
Sorry, I missed the UX label and went about testing this....but could you please look to see if you have more to add

**Comment by Malar-Natarajan** [comment]
Verified in QA

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
