### ISSUE TITLE
Line breaks/padding whatever for book pages

### ISSUE THREAD

**Issue by lwtchu** [openstax/business-intel#264]
### Description

Description box line breaks aren't showing up on the site.

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [x] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:**  use any admin username
- **URL:**  openstax.org/admin - go to economics book
- **Course number:**  there are no courses on bit
- **Course type:**  nO coUrSeS On BIT

- **Steps**

idk make some paragraphs or something in the description box 
----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
no impact. i just think it looks ugly

----------------
**Images or Screenshots** (_attach below_)

![screen shot 2019-02-14 at 10 03 38 am](https://user-images.githubusercontent.com/11299125/52799633-d5d3a100-303f-11e9-80ff-e7c65077004c.png)
![screen shot 2019-02-14 at 10 03 42 am](https://user-images.githubusercontent.com/11299125/52799634-d5d3a100-303f-11e9-9496-f67c82a29052.png)

----------------
### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by mwharrison** [comment]
@lwtchu - would you mind making sure this works for you on cms-dev.openstax.org?
Ping me if you don't know how to log in with admin. :)

**Comment by victoria-cooke** [comment]
@mwharrison I thought Larissa would be reviewing the change for this. Does it still need UX review as well?

**Comment by mwharrison** [comment]
@victoria-cooke - whoever gets to it first :)
I think this is getting released tomorrow morning... so maybe it just needs to move on?

**Comment by victoria-cooke** [comment]
@mwharrison Gotcha, didn't realize it was so soon. I just reviewed it on dev and it looks like the formatting in Wagtail visually matches up with what's on the book details page for the Principles of Economics 2e book only. Checked a few other books and noticed the empty <p> tag with 8px padding did not carry over to those.

**Comment by berkalpyakici** [comment]
@victoria-cooke Can you send me the links of the books you checked?

**Comment by victoria-cooke** [comment]
@berkalpyakici 
- Principles of Macroeconomics 2e: https://cms-dev.openstax.org/details/books/principles-macroeconomics-2e
- Principles of Microeconomics 2e: https://cms-dev.openstax.org/details/books/principles-microeconomics-2e

**Comment by berkalpyakici** [comment]
Oh actually, that's 8px padding that we added. I can just go ahead and double that. Some other books (where you see a large padding have <br> tags.

**Comment by berkalpyakici** [comment]
@victoria-cooke Oh actually, that's 8px padding that we added. I can just go ahead and double that. Some other books (where you see a large padding have <br> tags.

**Comment by berkalpyakici** [comment]
Can you check it again @victoria-cooke ?

**Comment by victoria-cooke** [comment]
@berkalpyakici I see the change on Principles of Macroeconomics 2e; it looks like a `<br>` tag was added inside the `<p>` tag. However, it doesn't look like the change was applied to any of the other book details pages. Principles of Economics 2e is still utilizing the empty `<p>` tag, and the formatting of the other books is unchanged. Guessing that it's not possible to change the spacing globally for book details? If it were possible to bump up the padding-bottom rem some on the first paragraph for all summaries, I think that might do it.

**Comment by berkalpyakici** [comment]
@victoria-cooke We can bump up the padding-bottom, but then, we might end up having some inconsistencies in between different books. The differences across different books are the result of how a new paragraph is initialized when the content is added on admin panel. If the line-break button is used, it adds <br> tags, that add a rather large gap. If it is not used, then we just rely on <p> tags. I'll look into how we can deal with spacings and get back to you.

**Comment by berkalpyakici** [comment]
@victoria-cooke Can you verify the changes on dev again? Thanks

**Comment by victoria-cooke** [comment]
@berkalpyakici Looks like the fix went through; everything's good to go. Thank you!

**Comment by ejp3** [comment]
Verified in QA

**Comment by ejp3** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production
