### ISSUE TITLE
Hide publication date on book pages from Google

### ISSUE THREAD

**Issue by CourtneyRay** [openstax/business-intel#265]
### Description
Currently in search results, our book details pages show up with the original book publication date as the date of the page, which makes the pages look like they haven't been updated in years. This affects click-through which affects our search rankings. 

We should explore how to change this. We could
a) Hide the dates from Google (make the date an image? include in an iframe?)
b) Mark up another date with schema markup so Google will prioritize. Date the book was last updated? 
c) another option not heretofore mentioned

![Screen Shot 2019-02-14 at 3.38.08 PM.png](https://images.zenhubusercontent.com/5b7ed2d5bc512f725222c253/b6176b68-2da1-4010-82f9-067e9eae491d)

### Acceptance
- Original book publication date is no longer available to Google as book details pages publication date
- Ultimately - Google no longer displays original book publication date as the page date for book details pages in search results

### Impact
impacts our search results and likelihood for people to click

* **Severity**: [ ] High [x] Medium  [ ] Low

### Checklist for Done

1A-DEFINE
- [x] Description is complete
- [x]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [x] The work is broken into reasonable and consistent work items.
- [x]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [x]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [x]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by RoyEJohnson** [comment]
https://webmasters.googleblog.com/2019/03/help-google-search-know-best-date-for.html

**Comment by Brooke-Fail** [comment]
Will verify in Production.

**Comment by Brooke-Fail** [comment]
After deployment to production, google searching anatomy and physiology still the April 2013 as the most recent date. 
Screenshot:
![Screen Shot 2019-04-23 at 9.33.58 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/6d197b03-07f8-4b81-97cb-22ce1685d31e)

**Comment by RoyEJohnson** [comment]
Google updates periodically, not immediately. It will take some time for an updated index to appear. I think we can request a new scan to hurry that process along.
