### ISSUE TITLE
Consider including full TOC on book details pages for SEO purposes

### ISSUE THREAD

**Issue by CourtneyRay** [openstax/business-intel#269]
### Description
Now that our book content is moving to openstax.org (REX), Optidge believes it would benefit us to have a full hyperlinked TOC in the main content of each book pages, since that is now the primary informational page about the book that we want people to land on. This will help our searchability for topics across the book, and also signal to Google that this is a useful reference page connected to all of those topics.

They recommend that we could add it as an additional tab, but we are going to have it slide in from the left.

Visual design: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5cf823806af3e11bb4adcfa1

### Acceptance Criteria
- Table of contents remains under the Book detail section menu, but rather than having a modal popup, the TOC panel slides in from the left, squeezing the rest of the page content (desktop mode only; TOC is in an accordion group on mobile)
- The Table of contents is hyperlinked

### Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by RoyEJohnson** [comment]
Talk to @philschatz about data source for TOC (and in particular the links)

**Comment by allisonhowell** [comment]
@victoria-cooke Moving back to Design per our decision to take another look at this.

**Comment by victoria-cooke** [comment]
@allisonhowell TOC design is ready to go on Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/screen/5cf8237e2d86001d8c6feddf

**Comment by allisonhowell** [comment]
@RoyEJohnson This design is approved - moving to design done. This is high priority.

**Comment by RoyEJohnson** [comment]
@victoria-cooke The TOC panel is running on dev, for your review.

**Comment by victoria-cooke** [comment]
@RoyEJohnson First round of review is complete. Changes are on Trello: https://trello.com/b/Vr2DfPT7/ux-review-toc

**Comment by RoyEJohnson** [comment]
@victoria-cooke I got it to behave nicely. It is on cms-dev. Brooke will be testing this version, too, so probably cms-qa soon.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Second round of review complete: https://trello.com/b/Vr2DfPT7/ux-review-toc

**Comment by victoria-cooke** [comment]
@RoyEJohnson Third round of review complete: https://trello.com/b/Vr2DfPT7/ux-review-toc

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by victoria-cooke** [comment]
Decided in parking lot today to add the padding update in the next release. cc: @RoyEJohnson @allisonhowell

**Comment by ejp3** [comment]
Verified in Staging

**Comment by ejp3** [comment]
Verified in Production
