### ISSUE TITLE
Streamline footer and add a link to Help

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#271]
# Description
The Unified team needs to bring over the footer from OpenStax.org, but its size impacts the student reading experience. We want to streamline the footer so that it takes up less space, but still gives website visitors the essential information. 
# Acceptance
- A link to Help is added to the footer
- Licensing, Terms of Use, Privacy Policy, Accessibility Statement, Careers, Contact Us, Press all stay in the footer
- The following language stays in the footer: 

OpenStax at Rice University is a 501(c)(3) nonprofit charity

© 1999-2018, Rice University. Except where otherwise noted, textbooks on this site are licensed under a Creative Commons Attribution 4.0 International License.

Advanced Placement® and AP® are trademarks registered and/or owned by the College Board, which is not affiliated with, and does not endorse, this site.

**Hi-Fi**: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5ca360c27ad7e610e22a2a7f

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [x] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [x] Distilled acceptance tests are added to the issue.
- [x] Automated testing criteria are added to issue.
- [x] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

* **Severity**: [ ] High [ ] Medium  [ ] Low

**Comment by allisonhowell** [comment]
@victoria-cooke FYI on this issue. I'd like to discuss briefly with you before I add all the acceptance criteria.

**Comment by victoria-cooke** [comment]
@allisonhowell I went through and checked off some of the Define items. Can you verify that this is all that needs to be checked? Also, will future items be placed in the Define Done column for me to pull from, or will you move them to Design?

**Comment by victoria-cooke** [comment]
@RoyEJohnson @allisonhowell Hi-Fi is on Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5ca360c27ad7e610e22a2a7f

**Comment by victoria-cooke** [comment]
@RoyEJohnson @allisonhowell UX review cards are up: https://trello.com/b/Vr2DfPT7/ux-review-footer-ip-program

**Comment by RoyEJohnson** [comment]
@victoria-cooke I attached my new PR (UX fixes for footer and IPP page, round 2) to this one.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by itsgeraldwang** [comment]
Verified in Production.

**Comment by victoria-cooke** [comment]
@meeragovindaraju points updated
