### ISSUE TITLE
Redirect Report Broken

### ISSUE THREAD

**Issue by lwtchu** [openstax/business-intel#274]
# Description
Hello there was some steam losing-ness in this conversation. https://openstax.slack.com/archives/C69BU01RC/p1550091078058000

Redirect reports did not come in on February 1 and March 1

**SCENARIO** _Briefly describe the issue._

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

Idk ?? We just didn't get the email. We can wait for March 1 to see if we don't get it again. 
it should go to `cmsupport@openstax.org` on the first of every month.

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**
We cant fix the broken links 

----------------
**Images or Screenshots** (_attach below_)

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
~~- [ ] If UX design is needed then the UX label is added~~
~~- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.~~
~~- [ ] A high-level solution (development approach for the code change) is added to the issue~~
~~- [ ] If prototype code is generated, it is linked to the issue.~~
~~- [ ] If tech briefs are generated, they are linked to the issue.~~

1B-DECOMP
~~- [ ] The work is broken into reasonable and consistent work items.~~
~~- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.~~
~~- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.~~
~~- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.~~
~~- [ ] If an issue is included in a product phase, then Release is selected.~~

1C-DESIGN
  ~~- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.~~
  ~~- [ ] Distilled acceptance tests are added to the issue.~~
  ~~- [ ] Automated testing criteria are added to issue.~~
  ~~- [ ] The solution is updated.~~

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by lwtchu** [comment]
@allisonhowell hey not sure who is working on this - but CS is getting the report in their inbox. Just wanted to clarify that it should go to `cmsupport@openstax.org` on the first of every month.

**Comment by mwharrison** [comment]
Per Marc @ scrum on 3/26: Redirect report I think got sent to customer service, but should go to cmsupport@openstax.org

**Comment by lwtchu** [comment]
Also another note - i think jeff is getting it every  day - it should be once a month :D

**Comment by marcjeannott** [comment]
Content Managers did receive the email, but we received four separate emails back to back containing the same content. Talked to Micheal about this already

**Comment by Malar-Natarajan** [comment]
@mwharrison 

reopening this card based on Marc's comments above

**Comment by mwharrison** [comment]
@marcjeannott - we (think) were able to stop the old server from sending these emails out - can you let me know if customer service gets anymore?

**Comment by marcjeannott** [comment]
@mwharrison CS is still getting it but daily anymore, last one was on Tuesday from noreply@openstaxcollege.org. 

CMs are receiving the right one, but we got three copies of it on the first.

**Comment by mwharrison** [comment]
@marcjeannott - that would have been about when the emails were shutoff, so sounds like it was successful!

I'll look further into why CMs are getting three emails.

**Comment by mwharrison** [comment]
@berkalpyakici discovered cron was running on dev and QA, likely contributing to the three reports being sent out. The cron has been shut off, waiting for June 1st to verify.

**Comment by mwharrison** [comment]
@marcjeannott confirmed they only got one email this month. Closing this issue!
