### ISSUE TITLE
Complete UX review updates for spring re-engage campaign 

### ISSUE THREAD

**Issue by victoria-cooke** [openstax/business-intel#280]
# Description
The spring re-engage campaign is the most important campaign that the marketing team runs every year. This year, the challenge is presenting the OpenStax journey to potential adopters in a fresh and unique way. We want to make our internal adoption milestones meaningful, interesting, and fun for our prospective adopters.

Using the tools available to us, we can personalize the OpenStax experience, guiding them all the way from account creation to adoption.

Using Accounts, Salesforce, Pardot, and OpenStax.org, we will deliver a personalized experience to contacts in the campaign. By logging into our accounts system from a link delivered through email, contacts will be able to see where they are on the OpenStax adoption journey and be encouraged to finish the journey.

**Review List:** https://trello.com/b/Vr2DfPT7

# Checklist for Done
4A-UX REVIEW
  - [ ] All To-Do items on Trello have either been placed in Done or Backlog.
  - [ ] Decide when Backlog items should be addressed or revisited.
  - [ ] The pull request is merged into master, and the change branch is deleted.

**Comment by Brooke-Fail** [comment]
There were a few issues I found.

1. The Hero Badge does not animate upon completion. Video below. 
Video:
https://drive.google.com/file/d/1ru_X5Z3jym3grenJYt5OYc_lRb-AXbiQ/view?usp=sharing

2. Blank details box after submitting your address on the "Mail my Hero Badge" form. Screenshot below.
Screenshot:
![Screen Shot 2019-04-04 at 3.49.46 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/679df82f-102d-40c5-81f8-65946221cc5a)

**Comment by Brooke-Fail** [comment]
Verified in QA, the Hero Badge animates properly. The other issue for www2 is still occurring.

**Comment by Brooke-Fail** [comment]
Verified in Production.
