### ISSUE TITLE
Add commas to student savings numbers in interactive map

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#281]
# Description
The students savings numbers in the interactive map do not look like money because there are no commas. Also, if there is a 0 (like $12.50), it only shows 12.5. See attached screenshots.
# Acceptance Criteria
There are commas and the zeros have been added back in. 
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN a user looks at a particular school on the interactive map
> AND the student savings number is over $999.00  
> THEN the number displays with a comma: $1,000.00, $900,000.00, etc.
> WHEN a user looks at a particular school on the interactive map
> AND the students savings number has a zero at the end  
> THEN the zero appears 

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**QA needs checklist:**
  - [ ] Acceptance Criteria are complete
  - [ ] Milestone should be tagged for PR's 
  - [ ] Milestone should be tagged for issues
  - [ ] Content update needed
  - [ ] Content update complete

**Deployment needs**
  - [ ] Pre-deployment tasks
  - [ ] Data migrations 
  - [ ] Post-deployment tasks

**Comment by allisonhowell** [comment]
![Screen Shot 2019-03-05 at 6.03.46 AM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/0927c3f4-0e52-48ac-ace3-4e7f71feee95)

![Screen Shot 2019-03-05 at 6.04.42 AM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/d8022464-190c-484b-846a-2da4d4ee36a1)

**Comment by Brooke-Fail** [comment]
Verified in QA and Production.
