### ISSUE TITLE
Rollout Pulse Insights 

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#316]
# Description
We want to create a customer feedback loop that delivers meaningful, real-time responses that result in actionable data. We want to understand how our customers feel about our website and products when they’re in them, giving us insight into how their experience impacts overall brand satisfaction and our adoption numbers. We need this feedback quickly so that we can take timely action to improve the customer experience and help drive daily business decisions. 

We have purchased a third party tool, Pulse Insights, to help us measure brand satisfaction and user experience, as well as become a replacement for the A/B testing tool Optimizely. 

Pulse Insights will be available for us on OpenStax Tutor and within our books, but will be monitored by marcom/BIT. 

# Epic Doc
https://docs.google.com/document/d/1I4ZHTx2ebp0Nz_WVLOItY4CWg1lW49jvPwoRfp5NuPw/edit# 

# Acceptance Criteria
- The first collection of surveys have been launched on openstax.org.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by dkhowala** [comment]
@snm8 Updated the questions for Tutor
@carlycurran Can you review, please?

**Comment by allisonhowell** [comment]
![OpenStax Adopters vs. Non-adopters Desktop.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/0544adf9-9d25-4c90-ba4d-ffe0520e6f6a)

![OpenStax Adopters vs. Non-adopters Mobile.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/20247b6f-7af6-4351-b14f-ae3e87e18cab)

![OpenStax Adopters vs. Non-adopters Tablet.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/5c6e0401-844d-46b0-9c26-9502ad75d076)

@victoria-cooke Please provide comments to get this within pattern library standards. Thanks!

**Comment by victoria-cooke** [comment]
@allisonhowell The devs should pull from the pattern library, but here are the basic settings for:

1. **The title**
Use OS Web h3 font
2. **The orange buttons**
`border: 0;`
`border-radius: 0.2rem;`
`color: #fff;`
`font-family: 'Neue Helvetica W01', sans-serif;`
`font-weight: bold;`
`font-size: 1.6rem;`
`text-align: center;`
`background-color: #f36b32;`
3. **The modal**
Default
`border-radius: 2px;`
`background-color: #fff;`
`box-shadow: 0 2px 6px 0 rgba(0, 0, 0, 0.25);`
`padding: 40px;`
Active/Hover
`border-radius: 2px;`
`background-color: #fff;`
`box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.25);`
`padding: 40px;`
