### ISSUE TITLE
Multiple issues with the interactive map

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/business-intel#320]
# Description
There are multiple issues with the interactive map.

**SCENARIO** _Briefly describe the issue._
1. Searching Hong Kong or college station will zoom in on the wrong location (in the ocean)
2. Moving the map with the right mouse button will eventually duplicate the image of the map(screenshot attached)
3. Clicking on one of the pink dots does not load appropriate data. I clicked on a dot in New Jersey and the map shows a school in Texas
4. Searching moorestown and the map keeps zooming in
5. US map is covered when we expand & apply the filters
6. Null displayed in city may be when salesforce doesn't have city data. Can we ignore city in those cases? (Cardiff university, cherokee community school Iowa)
7. When we apply any of the filter conditions and look at the map the pink dots are not even visible
8. When we search for a school/state/city (eg. texas) the list shows the appropriate data but no pink dots are visible in the map
9. As per test plan there are few schools that should have a testimonial displayed. But no testimonial is displayed. See the list here: https://docs.google.com/document/d/1OhuN_LS0_rPGGxQz56eFp9QX0_Ha2ePaLNQ56HonPC0/edit?pli=1

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_
Duplicate map steps:
1.  Go to the interactive map
2.  Zoom out as far are you can
3. Hold the right mouse button around North America and move the mouse up. This will rotate the map.
4. Notice how the map starts to duplicate itself 

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [x] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  
73.0.3683.75
----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
![Untitled.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/f46ca26e-d2c9-4e27-9a59-7ba0c2ac11d8)

# Checklist for Done
1A-DEFINE
- [ ] Description is complete
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by mwharrison** [comment]
Most of the issues identified here are due to incorrect location data in Salesforce.

**Comment by CaptainXep** [comment]
In addition to all of the bugs described by Brooke, there are a couple more that needs to be addressed:
1. The mouse pointer changes on hover over dots but clicking on it yields no change.

2. The "Close map" button stops working after searching for a school (Tried College Station in testing).

3. Applying "Has testimonials" filter moves map into the middle of the ocean.

4. Random large dot in the ocean (see below)
![Screen Shot 2019-05-16 at 10.34.22 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/d87e14ac-a099-4172-80e2-24688eb104a1)

5. Clicking on the "Apply filter" button (when filters are selected and when none are selected) leads to map bugging out for a couple of seconds before removing the dots.

6. Clicking on the "Apply filter" button (when filters are selected and when none are selected) reorients map cardinal directions but doesn't reorient z-axis (see below)
![Screen Shot 2019-05-16 at 10.46.17 AM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/e3aa3abf-41d6-4157-90fd-81fdcd88354c)

**Comment by ejp3** [comment]
Here's a couple more bugs from the filters
1. When you check schools that have saved over $1 million on filters, it still shows schools that have saved less than $1 million.
2. Community colleges show up for both College/University and Technical/Community College institution types. 
3. Some colleges show up for the High School institution type.

**Comment by ejp3** [comment]
We split these bugs into their own cards, so I'm going to close this one.
