### ISSUE TITLE
ERRATA TOOL UPGRADE: Add the Ability to Block Users from Submitting Junk/Spam Errata

### ISSUE THREAD

**Issue by openstaxalina** [openstax/business-intel#323]
# Description
Sometimes users repeatedly submit errata that is not valid or useful.  It may contain profanity or irrelevant statements.  Reviewing, cleaning, and/or archiving such reports is not an efficient use of maintenance time and resources.  Therefore, we may consider adding the option to block users from submitting additional errata if they do not abide by the tool's terms of use.

# Acceptance Criteria
- Content Managers can designate a user, by userID or other method, to be prohibited from submitting additional errata reports.
- Content Managers can update this setting themselves, or communicate with another appropriate staff member who can do this.
- Once the user is identified, the process to block a user from submitting errata should not take more than five minutes. 
- TBD: The user will receive an email notifying them they've been blocked from submitting additional errata and providing a link to a KBR or the support email.
- When the user revisits the tool, they receive a message alerting them that they've been prohibited from submitting additional errata due to violating errata tool policies, and providing a link to the relevant KBR ad/or to the support email.
- The user is not able to submit additional errata reports.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by yblock** [comment]
The consensus online seems to be that blocking users by IP at the firewall/server level is the best way to handle this. However, if that is not an option, it would be possible to hard-code someone username and immediately archive any of their submissions.

**Comment by yblock** [comment]
decided the best way to do this would be the "shadow-ban" method of insta-archiving their submissions

**Comment by berkalpyakici** [comment]
Backend work is complete. @RoyEJohnson, backend will return `400 Bad Request` if the account is blocked from submitting an erratum after form submission.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
