### ISSUE TITLE
Add book text color to OpenStax.org CMS

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#333]
@sadierichardson commented on [Mon Mar 25 2019](https://github.com/openstax/unified/issues/224)

# Description
REX needs to know the book foreground color so we can create the book banner in REX. The OSweb CMS does not currently have this information (only the background color).

# Acceptance Criteria
- REX can call each book’s foreground color to create the book banner in REX

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-PRE DESIGN
- [x] Description is complete
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
  - [ ] The work is broken into reasonable and consistent work items, and work item issues created. The work item issues are moved below the Done marker in the Decomp column.
  - [ ] Estimate is updated for the work item issues.
  - [ ] If there is a parent story epic issue, it is linked with the child work item issues and moved to the Epic column.
  - [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
  - [ ] Distilled acceptance tests are added to the issue.
  - [ ] Automated testing criteria are added to issue.
  - [ ] The solution is updated.

2A-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] The acceptance tests are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

2B-PROD ACCEPT
  - [ ] The pull request is merged into master by the Product Manager, and the change branch is deleted.

3A-PEND RELEASE
  - [ ] All the changes in the release are deployed to the Release Candidate environment.
  - [ ] The release is declared frozen by the Product Manager.

3B-RELEASE REVIEW
  - [ ] Acceptance tests pass for all issues in the release
  - [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

<!--
If this story becomes an epic, delete the steps from 1C-DESIGN onward, then uncomment the following.
TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by mwharrison** [comment]
The text on the book covers are images, this will just be a field that will need to remain updated by someone.
(cc: @TomWoodward @kjdav @allisonhowell)

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
