### ISSUE TITLE
Data update for short-code redirects

### ISSUE THREAD

**Issue by reedstrm** [openstax/business-intel#341]
# Description
Short-code redirects (links - i.e. https://openstax.org/l/link-here) that redirect for simulations to https://archive.cnx.org/specials/uuid/rest-of-link-here) currently cause a redirect-through-http
if the initial target does not have a terminating '/'. This will be fixed in cnx nginx config, but in the mean time, can we get a content fix in the openstax-cms DB, updating all simulation targets to end in '/' ?

# Acceptance Criteria
All simulation short-code links have a terminal slash

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If the issue is included in a product phase, then Release is selected.

2A-NON CODE
- [ ] The work is completed and satisfies the acceptance tests.

**Comment by mwharrison** [comment]
Ran `select * from wagtailredirects_redirect where redirect_link not like '%/' and redirect_link like '%archive.cnx%';` to identify the links.
Then ran `UPDATE wagtailredirects_redirect set redirect_link = redirect_link ||'/'  where redirect_link not like '%/' and redirect_link like '%archive.cnx%';` to update those links.

All looks good.
