### ISSUE TITLE
There are a few issues with the Hero Journey step milestone titles

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/business-intel#354]
# Description

**SCENARIO** _Briefly describe the issue._
Issue 1: Hero Journey step milestones appear to drag between steps instead of smoothly fading in and out.

Issue 2: Hero Journey step milestones will display undefined as their title right before they fade out

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_
1. Go to cms-staging.openstax.org/hero-journey 
2. Log into an account that has completed 3 or more steps in the process. (user bf22+22@rice.edu)
3. Click on a step (like step 4) and drag mouse up towards step 2
4. Notice how the step milestones can drag to the next one while leaving a trail
5. Hover over a step
6. Move the mouse over to the left of the step number
7. Notice when the step milestone title changes to undefined before fading out
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)
Issue 1: drag
Screenshot:
https://drive.google.com/file/d/11MZpOdEQOCOrgb022xL0GVGxIsqbazmU/view?usp=sharing
Video:
https://drive.google.com/file/d/1sm8dSygD_nw0_cRrwMbZDkp38c71WScr/view?usp=sharing

Issue 2: undefined
Video:
https://drive.google.com/file/d/1fELwWYfv9eH5eK-m_mlNETjn-grqX8Ia/view?usp=sharing

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by RoyEJohnson** [comment]
Turned on 3d graphics engine to eliminate the trail.
Tooltip text reverts to whatever page you're looking at as it fades out.

**Comment by CaptainXep** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by ejp3** [comment]
Verified in Production

**Comment by ejp3** [comment]
Verified in Production
