### ISSUE TITLE
Accounts should not state the users name on the screen after entering their email address

### ISSUE THREAD

**Issue by mwharrison** [openstax/business-intel#358]
# Description
To prevent the accidental exposure of personal information, we want to change the "Hi, <name>!" line from the screen after entering your email address so that it doesn't show the user's name.

![image (2).png](https://images.zenhubusercontent.com/5bacf5ada3f3a02e15d4848f/a801abb6-bac8-4fe4-9f4e-085742becf92)
_Login, screen 1_

![image (1).png](https://images.zenhubusercontent.com/5bacf5ada3f3a02e15d4848f/4f3c6cc8-07b7-402a-bfb1-b54396af93c7)
_Login, screen 2 (remove "Hi, JP!")_

UX should also look at this to verify the user flow is clear.

# Acceptance Criteria
The user is not identified after inputting an email address.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by mwharrison** [comment]
@victoria-cooke - Can you confirm that it would be okay (from a UX perspective) to change this to "Hello, <user email address>!"?

**Comment by victoria-cooke** [comment]
@mwharrison Yes, the email works.

**Comment by allisonhowell** [comment]
@mwharrison Per Victoria's comments above, I'm moving on to Design Done to work on when you're freed up.

**Comment by BryanEliDimas** [comment]
Note that it's not the `user`'s **name** being shown, but the `user`'s **username** — and only if they have 0 verified email addresses. See https://github.com/openstax/accounts/blob/1dd7451de2653a6cbbe9a807ee6e8521df944534/app/routines/get_login_info.rb#L35
Also note that if there user is 1) unverified and 2) has no username, then the message on the page will still present the welcome message but it will have a space between "Hi" and the exclamation mark.

> Hi !

**Comment by BryanEliDimas** [comment]
Forget what I just said. I believe it presents the `user`s **standard_name** which is basically their name https://github.com/openstax/accounts/blob/0dca60a72a62b5047d937ba3661728e40de2bca1/app/models/user.rb#L164

**Comment by BryanEliDimas** [comment]
Actually, if they have no `title` or no `last_name`, then `username` will be used... but they don't have a username then the message will be **"Hi !"**

**Comment by BryanEliDimas** [comment]
PR for this issue is done and merged.

**Comment by Brooke-Fail** [comment]
Login shows the user's email instead of name when in the process of logging in. Verified in QA.

**Comment by ejp3** [comment]
Verified in Staging

**Comment by Brooke-Fail** [comment]
Verified in Production.
