### ISSUE TITLE
Tracking User Auto-verifying Students with OS accounts in Salesforce, giving them access to Instructor Resources

### ISSUE THREAD

**Issue by khannum19** [openstax/business-intel#369]
# Description
Students are creating an account on OS Web and then requesting access to instructor resources. Tracking User is confirming their faculty status (because they are a contact in Salesforce), giving them access to instructor resources. 
# Acceptance Criteria

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by bonnebbrown** [comment]
![2019-05-08_13-52-26.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/96ecaa4a-7f0a-49d8-8b16-b3ccbb965e43)
![2019-05-08_13-50-50.png](https://images.zenhubusercontent.com/5bad045177c9d97356bc41df/9972377e-1278-4112-9dd0-35e78eb9d121)

**Comment by bonnebbrown** [comment]
More examples:
Lead URLs: GC: https://na48.lightning.force.com/lightning/r/Lead/00Q0B00000rJhu6UAC/view
WR: https://na48.lightning.force.com/lightning/r/Lead/00Q0B00000rJvNaUAK/view
AR: https://na48.lightning.force.com/lightning/r/Lead/00Q0B00000rJzIRUA0/view
LS: https://na48.lightning.force.com/lightning/r/Lead/00Q0B00000rK6jWUAS/view

Contact URLs: GC: https://na48.lightning.force.com/lightning/r/Contact/0030B00002Lu3SXQAZ/view
WR: https://na48.lightning.force.com/lightning/r/Contact/0030B00002LtT2JQAV/view
AR: https://na48.lightning.force.com/lightning/r/Contact/0030B00002OVYpkQAH/view
LS: https://na48.lightning.force.com/lightning/r/Contact/0030B00002PSn1eQAD/view

The status has changed in SF and accounts, as I had to manually change their access to the Instructor Resources.

**Comment by khannum19** [comment]
More Issues related to students:

1. When a student is auto-verified and shows up in leads, the organization "Students" is removed from their faculty lead.

Since the organization "Students" does not show up in the lead, the student is not prevented from being given access to instructor resources 

2. In accounts, a student listed their role as "other" but in Salesforce, the contact has "Students" as the organization - what are the requirements for someone to be lumped into "Students" organization
