### ISSUE TITLE
Define partner portal for lead sharing with OpenStax Allies

### ISSUE THREAD

**Issue by BruceP99166** [openstax/business-intel#370]
# Description
Define [partner portal for lead sharing with OpenStax Allies](https://app.zenhub.com/workspaces/openstax-bit-5bacfe3f4b5806bc2bea3764/issues/openstax/business-intel/322)

# Acceptance Criteria
- Description complete
- Acceptance criteria complete

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] High-level natural language acceptance tests are complete
- [x] If the issue is included in a product phase, then Release is selected.

2A-NON CODE
- [ ] The work is completed and satisfies the acceptance tests.

**Comment by allisonhowell** [comment]
Description & acceptance criteria complete.
