### ISSUE TITLE
Change navigation on Rover by OpenStax marketing page

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#376]
# Description
We know from heatmapping that the navigation bar on the Rover by OpenStax marketing page is underutilized, and we also know that people aren't scrolling past the "meet Rover" section of the page. We want to find a way for users to get to the other important information on the page without sacrificing the content or design. An easy way for people to see what's on the page is to provide a clear, horizontal menu that gives the title of each section of the page. 

See https://tophat.com/textbook/ for an example and attached screenshot.

# Acceptance Criteria
- The navigation bar that currently lives on the Rover page is removed.
- A horizontal menu is added to the page, right under the introductory text 
- The Learn More button is removed from the page
- The names of each section on the menu is editable in the CMS and we can add/remove as needed from the CMS
- The menu items link to different areas of the page
- We can track clicks on each menu item in Google Analytics ![Screen Shot 2019-05-12 at 8.44.25 PM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/ab1049fa-a9d3-4534-98a7-ca061bc76545)
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Updated Rover nav is on Zeplin. Let me know if you have any questions.
cc: @allisonhowell

**Comment by RoyEJohnson** [comment]
@michael @allison We should have a parking lot about the CMS side of this. I think we can add a `link_text` to each section. It can be optional; if it has no value, no link is created in the navigator.

**Comment by victoria-cooke** [comment]
@RoyEJohnson @allisonhowell This is good to go.

**Comment by allisonhowell** [comment]
@victoria-cooke Could we make this a little smaller? It feels so large.

**Comment by Brooke-Fail** [comment]
Functionally this is working, however there are a few places on the web and mobile where text is covered up by the Rover image. See screenshots below:

![Screen Shot 2019-05-31 at 4.18.18 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/fa0e5238-0b68-41b6-a39d-5e108f7fc50f)

![Screen Shot 2019-05-31 at 4.19.40 PM.png](https://images.zenhubusercontent.com/5c8693e3192b7d23ed8223e7/ef380f1c-de22-4576-90be-3d02d5baf21d)

Web view (not browser dependent):
https://drive.google.com/file/d/17TMyPTZhA1FFzm_Yy4VT5-GP6tq9mhPC/view?usp=sharing

**Comment by Brooke-Fail** [comment]
Fix verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by itsgeraldwang** [comment]
Verified in Production.

**Comment by victoria-cooke** [comment]
@meeragovindaraju points updated
