### ISSUE TITLE
Chapter numbering is inconsistent between CNX and osweb

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/business-intel#38]
**SCENARIO** _ Certain chapters are not numbered in CNX, based on rules that we do not have in osweb. That often means that they get numbered in the osweb TOC.

----------------
**Steps to Reproduce the issue:** _Compare the numbering in Table of Contents and View online link for University Physics books.
Chapter review at the end of each chapter is numbered in the Table of contents (openstax.org) but should not be since it should match the numbering in cnx.org

- **Product:**
` [ ] ` Accounts ` [ ] ` BigLearn
` [ ] ` Exercises ` [ ] ` CNX
` [ ] ` Payments  ` [ ] ` Tutor
` [ ] ` Highlight ` [X] ` Web
- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [X] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [X] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [X] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [X] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

----------------
### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by meeragovindaraju** [comment]
<img width="1363" alt="screen_shot_2018-08-14_at_2 13 07_pm" src="https://user-images.githubusercontent.com/33066187/46434545-87b9a300-c719-11e8-9998-a079bfb70a7a.png">
<img width="1340" alt="screen_shot_2018-09-19_at_12 41 21_pm" src="https://user-images.githubusercontent.com/33066187/46434550-8a1bfd00-c719-11e8-89f0-ed35f3ef8756.png">

**Comment by meeragovindaraju** [comment]
Trello Card
https://trello.com/c/CkvBOgbu/895-bug-chapter-review-in-university-physics-is-not-numbered-in-cnxorg-but-its-numbered-in-openstaxorg-copy-in-zenhub

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Issue still occurring. 
<img width="1369" alt="Screen Shot 2019-10-04 at 2 17 46 PM" src="https://user-images.githubusercontent.com/48449285/66234093-6c79ce80-e6b2-11e9-83b3-6fb9166d485d.png">

**Comment by Brooke-Fail** [comment]
Verified in Production.
