### ISSUE TITLE
Add popup when users sign into Rover from openstax.org 

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#391]
# Description
When users go into Rover from the Rover marketing page on openstax.org, they are often caught off guard when they are prompted to sign in. We want to make the transition from openstax.org to the product easier for users to understand by adding a transition page or popup that will let the user know what to expect. 
# Acceptance Criteria
- Users see a popup or intermediary page before they are prompted to sign into Rover when they attempt to access Rover from the marketing page on openstax.org. (This should appear whenever a user clicks "Sign in to Explore." 
- The transition explains why the user is being asked to sign in or create an account before they enter Rover. 

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
@victoria-cooke Copy/design guidance:

H1: You’re one step closer to using affordable, step-by-step math homework in your classroom! 
H2: Sign in to your OpenStax account or create an account to explore Rover. 
Buttons: 1) Sign in or create an account, 2) Maybe later
2) Maybe later - directed to a demo sign up. Want to get a quick overview of Rover with a member of the OpenStax team? Sign up here.

**Comment by allisonhowell** [comment]
![unnamed.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/c41e4fc0-d56d-4f33-931f-a73baa5e8c34)

Attached is the look and feel of the training wheels in Rover. The intermediary page or popup should be cohesive. Jemel can be consulted on this issue as he is designing the final training wheels.

**Comment by victoria-cooke** [comment]
@meeragovindaraju points updated

**Comment by victoria-cooke** [comment]
@allisonhowell For review: https://invis.io/EYSGKEM8M4F
1 - is in the original style
2 - is the new style with the old gradient
3 - is the new style with an updated gradient I made derived from the old colors

**Comment by victoria-cooke** [comment]
@RoyEJohnson @allisonhowell Design is available on Zeplin: zpl.io/VqYlgXY

**Comment by RoyEJohnson** [comment]
@mwharrison To add the popup page, we need some fields added to the Rover page in the CMS:
`headline` - text
`instructions` - text
`signInText` - text
`cancelText` - text
`backgroundImage` - image (doesn't need alt text because it is a background image)

You can make the names whatever makes sense to use, considering what's already in the page data.

**Comment by victoria-cooke** [comment]
@mwharrison @RoyEJohnson Updated screens available in Zeplin: https://zpl.io/aRzGp7K

**Comment by victoria-cooke** [comment]
@RoyEJohnson Review items posted on trello at: https://trello.com/b/Vr2DfPT7/ux-review-rover-pop-up

**Comment by victoria-cooke** [comment]
@RoyEJohnson This is looking good. I added one more change to the column yesterday. Once that's done, this should be ready to push out.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Review item under the **Rover Pop-up** label in Trello: https://trello.com/b/Vr2DfPT7/ux-review-openstax-logo-rover-page-book-banners-rover-pop-up

**Comment by Brooke-Fail** [comment]
The code currently on production has been verified.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Already discussed, but one final to-do item in Trello: https://trello.com/b/Vr2DfPT7/ux-review-rover-page-book-banners-rover-pop-up-user-id-tracking-study-edge-blog-search-get-the-book-menu?menu=filter&filter=label:Rover%20Pop-up.

This should be good to go after that.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Looks good; this one's ready.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
