### ISSUE TITLE
Some community colleges show up for College/University and vice versa.

### ISSUE THREAD

**Issue by ejp3** [openstax/business-intel#409]
# Description

**SCENARIO** _Briefly describe the issue._
Some community colleges show up for College/University and vice versa on Apply Filters. 

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**

----------------
**Environment:**

- **Instance:**
` [ ] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by berkalpyakici** [comment]
School information needs to be updated on salesforce to fix this issue.

**Comment by chouston31** [comment]
@berkalpyakici which schools need to be updated?

**Comment by berkalpyakici** [comment]
I currently don't have the list of the schools that face this problem, so we can hold this card for a while. I'll get back to you when the rest of the cards are deployed on production, so that I can fetch the list.

**Comment by mwharrison** [comment]
@berkalpyakici - I think Salesforce only allows one type. Do you think the filter is doing a search for the word "College" - so it's returning both?

**Comment by berkalpyakici** [comment]
@mwharrison The problem is no longer that a single school is appearing in both searches, but rather appearing in the wrong one.

**Comment by berkalpyakici** [comment]
@chouston31 The map is now live on https://openstax.org/separatemap , so you can gather the list of incorrect schools by applying the filter.

**Comment by chouston31** [comment]
@berkalpyakici what am I filtering by?

**Comment by berkalpyakici** [comment]
@chouston31 ![Screen Shot 2019-06-20 at 10.10.02 AM.png](https://images.zenhubusercontent.com/5781032ebf93871ccd9dc757/79a78e71-d8ba-41fd-b4f7-83ac2e9aee3a) You can filter by using the filter menu and select the institution type. When I select College/University, I see 'Gila Community College' and 'Colorado Community College'. The list will scroll to list all institution filtered by that setting. ![Screen Shot 2019-06-20 at 10.10.16 AM.png](https://images.zenhubusercontent.com/5781032ebf93871ccd9dc757/81e9ffcc-1ae8-4394-9c73-96fd72ab3caa)

Also, some schools need location update. Rice, for example shows on South Annex instead of the main campus on 6100 Main.

I can also provide you with the correct locations of the universities in Turkey, as some of them are shown on wrong locations.

**Comment by chouston31** [comment]
I checked the first two in salesforce and they're showing them under community college. I'm not sure why they're showing up under college/university

**Comment by mwharrison** [comment]
@berkalpyakici - the problem with this is here: https://github.com/openstax/openstax-cms/blob/master/api/views.py#L121

It's doing an icontains search, instead of an exact search... so getting everything with "college" (depending on what the FE is sending)

**Comment by berkalpyakici** [comment]
I just looked at FE @mwharrison, and yes, the parameters were 'college' and 'technical'. I'll tell @RoyEJohnson to make the option values more specific for mapbox fe refactor.

**Comment by berkalpyakici** [comment]
Just posting here for future reference as well:
```
<option value="">All</option>
<option value="college">College/University</option>
<option value="technical">Technical/Community College</option>
<option value="high school">High School</option>
```
to
```
<option value="">All</option>
<option value="College/University">College/University</option>
<option value="Technical/Community College">Technical/Community College</option>
<option value="High School">High School</option>
```

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
