### ISSUE TITLE
Add Rover section on About Us page

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#411]
# Description
The About Us page on openstax.org does not include a box section about Rover by OpenStax. We need to add this to the page since Rover is launching in the fall and it's part of our suite of products. (See attached screenshot)
# Acceptance Criteria
- There is box section on the About Us page about Rover by OpenStax
- The section links to the Rover by OpenStax marketing page (/rover-by-openstax)
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
![Screen Shot 2019-05-29 at 2.20.51 PM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/91240ff8-5370-494f-b98f-18b67809fd24)

**Comment by allisonhowell** [comment]
@victoria-cooke A new card can be added in the CMS - this just needs a graphic from UX.

**Comment by victoria-cooke** [comment]
@allisonhowell  Uploaded some options for the Rover card: https://invis.io/M3SJS00BJVZ#/369725763_Rover-1

Will look into designing alternate icons for this and the IP card when I have an opportunity.

**Comment by allisonhowell** [comment]
@victoria-cooke Let's go with the orange and blue. When it's ready you can send to me to add to the CMS. Thanks!

**Comment by victoria-cooke** [comment]
@allisonhowell 
![20190612_BIT_RoverAbout_VCooke_v1-00.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/a9b736b1-3679-46c1-8af6-395f51ab6d2f)

**Comment by victoria-cooke** [comment]
@allisonhowell 
![20190612_BIT_RoverAbout_VCooke_v1-00.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/f225b93e-687b-4a6d-a45c-d9654586fd14)
