### ISSUE TITLE
Add new section for Institutional Partnership Program on About Us page

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#412]
# Description
The About Us page on openstax.org does not include a box section about the Institutional Partnership Program. Now that we have a page, we should add that to the About Us section. (See screenshot below)
# Acceptance Criteria
- There is box section on the About Us page about the Institutional Partner Program
- The section links to the Institutional Partner Program page (/institutional-partnership)

# Acceptance Tests

Acceptance Criteria

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
![Screen Shot 2019-05-29 at 2.20.51 PM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/da04f7d9-f460-4d53-b37c-3c84b3ebc95d)

**Comment by allisonhowell** [comment]
@victoria-cooke This can be added in the CMS, just needs a graphic from UX.

**Comment by victoria-cooke** [comment]
@allisonhowell Some color options for review: https://invis.io/M3SJS00BJVZ

I put placeholder text in the description for now.

**Comment by allisonhowell** [comment]
@victoria-cooke I like the third option (darker green), but am open to the lighter green if you think it fits better with the rest of the cards.

**Comment by victoria-cooke** [comment]
@allisonhowell Added one more color option for this: https://invis.io/M3SJS00BJVZ#/369725619_Ip-4

**Comment by allisonhowell** [comment]
@victoria-cooke So many options! I trust your design instincts on this one - let me know what you think will look best with the other cards.

**Comment by victoria-cooke** [comment]
@allisonhowell Updated IP page card image for posting

![20190612_BIT_IPPAbout_VCooke_v1-00.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/7908218a-9cbc-4b9c-bbb4-7f3217241f9a)
