### ISSUE TITLE
Report related to OKR 1

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/business-intel#419]
Note: This report is directly related to OKR #1. And specifically this part: Improve the depth of adoptions on campuses by increasing number of institutions adopting 10 or more books to 125 institutions total (May 2019 total is 42 institutions). And should align with this report that leadership is using: https://na132.lightning.force.com/lightning/r/Report/00OU0000002pO6M/view

Goal: Get a list of opportunities that are open at institutions where they already have 5-9 adoptions. 

Report name: Opps at schools with 5-9 adoptions

Type: Opportunity report

Criteria:
Domestic schools only
Schools with five or more ADOPTIONS
Open opportunities (excluding lost, won, recommend)
Four-year universities and community colleges only

Columns needed (in this order, please)
Opportunity name
Book
Number of students in opportunity
School
Parent Org.
Enrollment at the school
KIP?
Type (community college, four-year)
Number of adoptions

It's possible we may need to come back to this report a few times to get what we need.

Thank you so much!
Nicole

**Comment by chouston31** [comment]
@nicolefinkbeiner do you want opps at schools with five or more adoptions (as you state in the criteria) or schools with adoptions between 5 and 9 (as you state in the title)?

**Comment by nicolefinkbeiner** [comment]
Between 5 and 9. Thanks for asking!



	nicole finkbeiner
DIRECTOR, INSTITUTIONAL RELATIONS
OpenStax, Rice University      (713) 348-2972    openstax.org

**Comment by chouston31** [comment]
@nicolefinkbeiner how does this work for you? https://na132.lightning.force.com/lightning/r/Report/00O4P000004iFhCUAU/view?0.source=alohaHeader

**Comment by nicolefinkbeiner** [comment]
Thanks @chouston31 Question: Is there a way to also filter these opportunities so it doesn't show any opportunities related to a book that's already been adopted? For example, Fullerton College has a future adoption for Biology, so we want to exclude any Biology adoptions. The OKR says new books only (can't have any faculty who are currently using the book)

**Comment by chouston31** [comment]
@nicolefinkbeiner I'll slack you the csv file, because the file type isn't supported in Zenhub

**Comment by nicolefinkbeiner** [comment]
Thanks! Is there a salesforce link too? 



	nicole finkbeiner
DIRECTOR, INSTITUTIONAL RELATIONS
OpenStax, Rice University      (713) 348-2972    openstax.org

**Comment by chouston31** [comment]
@nicolefinkbeiner No, there isn't a way to do it in salesforce. In order to get what you want we had to export the first report that I sent you and a school adoptions report with all our adoptions. After that we had to do a search and vlookup to delete all the opportunities that had their book at their school.

**Comment by nicolefinkbeiner** [comment]
Ok. Thank you so much! This is wonderful!



	nicole finkbeiner
DIRECTOR, INSTITUTIONAL RELATIONS
OpenStax, Rice University      (713) 348-2972    openstax.org
