### ISSUE TITLE
Report Requests/Dashboard update

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/business-intel#436]
Report 1 (please also add to Nicole's Dashboard in SF)
Name: IP 10+ adoptions (not systems)
Goal: Number of Institutional Partner Schools (KIP) with 10 or more adoptions
Fields needed: Organization name, parent org, Number of adoptions

Report 2 (please also add to Nicole's Dashboard in SF)
Name: IP 5-9 adoptions (not systems)
Number of Institutional Partner Schools (KIP) with 5-9 adoptions

Report 3 (please also add to Nicole's Dashboard in SF)
Name: IP Adoptions
For the 2019-2020 school year
Fields needed: Parent org, Organization Name, Faculty name, Book, Students for 2019-2020 year (summarized)

Please delete the following from dashboard:
Partners - Currently using
Partners - Interest
Interest in Research
School Adoptions: All Time

Thank you so much!
Nicole

**Comment by chouston31** [comment]
https://na132.lightning.force.com/lightning/r/Dashboard/01Z0B000000WDkSUAW/view?queryScope=userFolders

@nicolefinkbeiner

**Comment by nicolefinkbeiner** [comment]
Thanks @chouston31!  For report #3, the sum of all yearly students isn't showing the total number of students impacted by all adoptions at IP schools. I'm pretty sure this is my error, as I asked for an adoption report, which means it wouldn't show every faculty member individually and thus total all students. Can you create a similar report that shows the total number of students impacted per year at IP schools? Sorry about that.

**Comment by chouston31** [comment]
@nicolefinkbeiner I've updated it to reflect student numbers on the dashboard. You will have to wait until the rollover happens to see an increase in that number, since it's for 2019 - 20

**Comment by nicolefinkbeiner** [comment]
Gotcha! Thank you!

When will the rollover happen?




	nicole finkbeiner
DIRECTOR, INSTITUTIONAL RELATIONS
OpenStax, Rice University      (713) 348-2972    openstax.org

**Comment by chouston31** [comment]
@nicolefinkbeiner by July 1st
