### ISSUE TITLE
SSO cookie is not set for user until a page refresh

### ISSUE THREAD

**Issue by mwharrison** [openstax/business-intel#444]
# Description
To duplicate:
- Make sure you are logged out
- Navigate to book detail page (eg. https://openstax.org/details/books/biology)
- Attempt to login via a locked resource
- Look in the inspector, SSO cookie is not set
- Refresh page, the cookie is set

# Acceptance Criteria
Cookie is set when a user logs in
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by BryanEliDimas** [comment]
@mwharrison I need a little more detail on this issue, please. cc: @allisonhowell 

1. First, are we positive that the issue is in Accounts? if so, could you please add the Accounts label and/or prepend **[Accounts]** to the issue title? Or does this require investigation to see where the problem is?
2. Could you please provide a URL for "Navigate to book detail page" to duplicate. That would help with the next item "Attempt to login via a locked resource" which I was not even aware that was an OpenStax feature before, so we have so many interacting products and I'm at this point I'm most familiar with CNX stuff.

Thanks!

**Comment by mwharrison** [comment]
@BryanEliDimas - this is completely exploratory, we are not sure if the problem is in accounts or in osweb. I thought we should start in accounts since that is where the cookie is set to begin with.

Here is the link to a book details page: https://openstax.org/details/books/biology

You'll have to use the inspector to look at when the cookie (`ox`) is set.

**Comment by BryanEliDimas** [comment]
@mwharrison Makes sense now, thanks!

**Comment by BryanEliDimas** [comment]
@mwharrison I believe the problem is in os-webview. `resource-box` components that are `locked` should have the html data attribute `data-local="true"`. I believe it could be added in `resource-box.js` perhaps like this:

```
attributes: {
                    href: model.link.url,
                    dataLocal: model.iconType === 'lock' ? "true" : "false"
                }
```

In [resource-box.js#L97-L99](https://github.com/openstax/os-webview/blob/28e69701d80d62be55b8dc909fd5dcd0af6e6268/src/app/pages/details/resource-box/resource-box.js#L97-L99)

Or directly in the html template `resource-box.html` somehow.

cc: @RoyEJohnson

**Comment by BryanEliDimas** [comment]
This branch contains my proposed solution, by the way: https://github.com/openstax/os-webview/compare/local_login_link?expand=1

I could not get os-webview up and running locally so I don't know if it actually works but the tests in Travis are passing.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
