### ISSUE TITLE
Report for OKR's

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/business-intel#457]
Hello!

Can I please have the following report?

Report name: Opps at higher ed US no adoptions

Type of report: Opportunities

Criteria:
School type: Four-year universities, technical/community colleges and for-profit colleges only
US and US territories only
Not equal to Denver University
0 current adoptions at the school (preferrably for the 2019-2020 year)

Fields:
Name of school
Type of school
State
Book
Number of students
Opportunity name
Faculty name

**Comment by chouston31** [comment]
https://na132.lightning.force.com/lightning/r/Report/00O4P0000063SYNUA2/view

@nicolefinkbeiner
