### ISSUE TITLE
Add OpenStax with StudyEdge app to openstax.org

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#460]
# Description
OpenStax is partnering with StudyEdge to release an app, which will feature OpenStax’s content on StudyEdge’s app. The app will be co-branded and will be featured prominently on openstax.org in the "Get this book" menu on the book details pages.

# Acceptance Criteria
- The OpenStax with StudyEdge app is added to the "Get this book menu" on openstax.org. 
- When a user clicks the on the app, they are taken to an intermediate page that gives more information about the app
- When a user chooses to continue, they are taken to the OpenStax with StudyEdge app in the app store. 
- App will not be released until Aug 7. Need to prevent it showing before then (but enable some way to test).
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by allisonhowell** [comment]
@victoria-cooke I have some ideas on other ways to drive traffic that'd I'd like to discuss with you before we finalize acceptance criteria.

**Comment by victoria-cooke** [comment]
@allisonhowell Followed up with Dani and Jemel. I'll be creating screens for:

- App placement on os web 
- The app image and title in the store 
- A pop-up page for the transition 

There will be two versions of each screen (except the pop-up). One for the ideal setup and a backup option in case the ideal setup isn't an option.

**Comment by victoria-cooke** [comment]
Screens for both versions: https://invis.io/RYSRZFWHSFG

**Comment by allisonhowell** [comment]
@victoria-cooke I'm going to move this back to prioritized while we wait to hear on StudyEdge's decision. Will move back and add final acceptance criteria then.

**Comment by allisonhowell** [comment]
@victoria-cooke Updated acceptance criteria and will talk with Dani on Monday about what additional text is needed on the popup page.

**Comment by victoria-cooke** [comment]
Discussed getting approval from marcom to make sure we're ok to use the App Store and Play Store badges on our site. @allisonhowell to follow up with Dani.

**Guidelines:**
https://developer.apple.com/app-store/marketing/guidelines/ 
https://play.google.com/intl/en_us/badges/

**Comment by allisonhowell** [comment]
We are approved to use the App store and Play store badges within their specified guidelines.

**Comment by victoria-cooke** [comment]
@allisonhowell Thanks, here are the updated screens. I got some feedback from UX and made a small update to the pop-up graphic. If marcom has confirmed that we fall within the requirements specified in both the Apple and Google badge guidelines, we should be good to go. 

I've put placeholders on the pop-up so that you can see where to drop the badges when you're ready to place them. Badge code can be found in the guidelines links I posted above.

Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5d2e240793f36756a802dbf4 @RoyEJohnson

**Comment by allisonhowell** [comment]
Yes, reviewed requirements and we are good to go. @RoyEJohnson This one is ready for you!

**Comment by victoria-cooke** [comment]
@allisonhowell Per our discussion, Study Edge branding has been removed. Ready for review at https://invis.io/RYSRZFWHSFG.

**Comment by allisonhowell** [comment]
Looks good. @RoyEJohnson Victoria updated the branding at the link above.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Zeplin has been updated as well; same link as before.

**Comment by victoria-cooke** [comment]
@RoyEJohnson Review items available under the **Study Edge** label in Trello: https://trello.com/b/Vr2DfPT7/ux-review-openstax-logo-rover-page-book-banners-rover-pop-up-user-id-tracking-study-edge

**Comment by victoria-cooke** [comment]
@RoyEJohnson One last change for this and we should be good to go: https://trello.com/b/Vr2DfPT7/ux-review-rover-page-book-banners-rover-pop-up-user-id-tracking-study-edge-blog-search?menu=filter&filter=label:Study%20Edge

**Comment by victoria-cooke** [comment]
@RoyEJohnson This one's ready to move on

**Comment by Brooke-Fail** [comment]
Verified in QA. Will do most of the testing on the 12th when the app is live.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by allisonhowell** [comment]
All links up and working on Monday, August 18.
