### ISSUE TITLE
Call out "View online" in REX books

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#464]
# Description
We want to help drive traffic to REX books as they're released without eliminating other book options or making the REX button larger. We also can't add any text like "new and improved" or other callout text. 
# Acceptance Criteria
- A "recommended" pop up can be applied in the CMS to REX books as they are released.  
- The pop up text can be edited in the CMS
- The pop up can have additional (optional) text underneath the "Recommended" text. 
- The pop up does not go away, but the user can close out of the pop up
- The pop up does not appear after the user's third visit to the page.
Zeplin design: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5d7bd07bbf15a3188178c774

# Acceptance Tests

 1. If a book is not Rex, there is no popup
 2. If a book is Rex, there is a popup the first three visits to the book
 3. Popup appears in both desktop and mobile views, per design
 4. There is an optional text field in the CMS for addition additional text to the popup
 5. If the user clicks the put-away "x", the notice stops appearing
 6. After the third visit to the details page for a particular book, the popup stops appearing

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by kjdav** [comment]
Allison, I noticed the requirement above that we can't add any callout text. Could we add callout text when we launch highlighting/note taking or other new features?

**Comment by allisonhowell** [comment]
@kjdav Yes, we can definitely add highlighting/note taking callout text per Suhani's mockups. This is just for REX books while the difference is still minimal to the user. We'll ramp up efforts as we release new features.

**Comment by victoria-cooke** [comment]
@allisonhowell Per our earlier discussion, pushed out some updated versions for this. Nothing drastically different; just refined a few things.

**Comment by victoria-cooke** [comment]
@allisonhowell Also, did you want the Study Edge treatment on a separate card? I know we're testing out the text block, but it didn't sound like the solution was set in stone.

**Comment by allisonhowell** [comment]
@victoria-cooke Let's do a separate card just in case.

**Comment by victoria-cooke** [comment]
@allisonhowell I've updated InVision with designs for the full word "Recommended". I've also added some color studies for the tooltip: https://projects.invisionapp.com/d/main#/projects/prototypes/18237356

**Comment by victoria-cooke** [comment]
Scope updated to include usertesting.com tests for view online text and callout options.

**Comment by victoria-cooke** [comment]
@allisonhowell User testing results are in. I still need to make a more detailed write up, but I already have the general points noted.

**Comment by snm8** [comment]
user testing designs right now

**Comment by snm8** [comment]
user testing results and recommendations ready - https://docs.google.com/document/d/1T4jgTdhTgk4vnFHZDFRiYDxbuXnLluMZssZF44-20_s/edit#heading=h.myqecjdgtlk8

**Comment by victoria-cooke** [comment]
**Kim/Allison decisions:**

- We want to move forward with the Recommended callout right away for REX books, but Allison wants to hold off on adding extra messaging to make it more clear why it’s recommended
- We want the desktop design to accommodate both the one word and the short blurb, and we like the design with the blue recommended callout
- I think I need to see what the mobile design for the blurb would look like (how do you have a tool tip icon on mobile, as y’all recommend). (**Note:** @snm8 mentioned sticking with the non-tooltip rectangle version for mobile based on UT findings)
- When we launch highlighting/note taking we will update the callout to include some light copy about the new feature (do y’all want some copy to include in the mobile mockup for this? if so i can work on this with allison input maybe)(**Note:** Same note above applies)
- Fine with not making it disappearing on 5 seconds
- I am not sure about not showing it after a user has seen it 3x? We forgot to talk about that, Allison. We should talk about that.

**Action Items:**

- **VC:** Create updated desktop tooltip designs for Recommended now that it will be static.
- **KD/AH:** Discussion about tooltip disappearing after user has seen it 3x.

**Comment by allisonhowell** [comment]
@victoria-cooke Option 3 is approved.

**Comment by victoria-cooke** [comment]
Awesome. And just confirming this is the design we're sticking with for all mobile versions?: https://invis.io/QRTX3RP2837

**Comment by kjdav** [comment]
Yes, I am good with the mobile version with just the blurb. (And option 3 looks great to me also, but it's Allison's call.)

**Comment by allisonhowell** [comment]
@victoria-cooke Yes, mobile version looks good.

**Comment by victoria-cooke** [comment]
@RoyEJohnson  Zeplin: https://app.zeplin.io/project/5c38d00ffbb8efbdff5e6627/dashboard?seid=5d7bd07bbf15a3188178c774

**Comment by mwharrison** [comment]
Issue moved to [openstax/devops #202](https://github.com/openstax/devops/issues/202) via [**ZenHub**](https://www.zenhub.com/)

**Comment by allisonhowell** [comment]
@mwharrison I don't think this was the right one to move to devops. Were you looking for the book redirect card?

**Comment by victoria-cooke** [comment]
@dkhowala Can you add your callout design to this card once it's complete?

**Comment by dkhowala** [comment]
@victoria-cooke: Link for the book details callout  https://projects.invisionapp.com/d/main#/projects/prototypes/18491697

**Comment by RoyEJohnson** [comment]
@dkhowala Can you make that public? It requires me to log in and then tells me I'm not a collaborator.

**Comment by dkhowala** [comment]
Open link for the Invision file: https://invis.io/VCTYT8Q64HJ

**Comment by Brooke-Fail** [comment]
The backend code for this is going out in the 9-25 release. However, the front end part will not be, this will not be user facing for the 9-25 release.

**Comment by snm8** [comment]
Just to confirm, this will appear on all book details pages until x'ed out or 3 sessions are done.
Also, unified team is thinking of doing a copy change every semester. So every time there is a change in copy, it will have to be launched again (including the first time when we will be adding the highlighting messaging). And the same requirements of x'ing out and shown until 3 sessions will be freshly in place each time it gets launched.
This will have to be added to acceptance criteria. 
@allisonhowell 
cc @kjdav

**Comment by allisonhowell** [comment]
@snm8 This was coded before the request to relaunch every time the text is changed. I think we'll have to make a separate card or enhancement for this functionality. I don't want to delay release to add that functionality in. 

Re: your clarifying statement, it was built so that if a user x's out of it, it will be permanently gone.

**Comment by snm8** [comment]
Ok. Fair enough. Would @kjdav be making the card?

**Comment by victoria-cooke** [comment]
@RoyEJohnson Review items have been posted at https://trello.com/b/Vr2DfPT7/ux-review-roy-view-online-callout

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by victoria-cooke** [comment]
@RoyEJohnson @allisonhowell Review complete; this one's ready to go.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
We are not ready to put Rex links in the cms just yet. Verifying based on staging testing, will reopen or create a new card if there are any issues.
