### ISSUE TITLE
Design and test student accounts prototypes

### ISSUE THREAD

**Issue by victoria-cooke** [openstax/business-intel#520]
# Description
Now that our initial testing and design phase is complete, student accounts is ready for high fidelity prototyping and testing. Our goal is to ensure that the proposed flow properly addresses the issues uncovered from previous testing, complaints to CS, etc.

- **Test Plan:** https://docs.google.com/document/d/1JdDdtoKW3sY508whJo4mxDvw6tI7SYJWnL3EAuhs_q0/edit#heading=h.cr66um96ahlw
- **Student Accounts Lo-Fi:** https://drive.google.com/file/d/1MQRvqt7EOvpuqytb3oxFdf_h-JrpFAhu/view
- **Student Accounts Hi-Fi (WIP):** https://invis.io/DST80SNBW6C
- **Student Accounts Prototype (WIP):** https://t48ysq.axshare.com/#c=2

# Acceptance Criteria
- Hi-Fi student accounts screens complete
- Interaction designs complete and published on Axure
- User tests run on usertesting.com
- Session notes, summaries, and recommendations written for all tests
- Findings shared with UX team, PDMs, and other necessary stakeholders

# Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] If UX design is needed then the UX label is added
- [x] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.

1C-DESIGN
- [x] Hi-Fi design of student accounts [lo-fi](https://drive.google.com/file/d/1MQRvqt7EOvpuqytb3oxFdf_h-JrpFAhu/view) screens have been created
- [x] Interaction design for screens completed and published on Axure
- [x] [Student accounts test plan](https://docs.google.com/document/d/1JdDdtoKW3sY508whJo4mxDvw6tI7SYJWnL3EAuhs_q0/edit#heading=h.cr66um96ahlw) divided by product
- [x] Tests for specific features created
- [x] Session notes linked on testing docs and summaries and recommendations are written for each
- [x] Findings shared with UX team, PDMs, and other necessary stakeholders

**Comment by snm8** [comment]
Decided that unified flow will be same as OS flow because:

OS and unified flow are no longer much different except very small things taken away (like +alternate email and checkbox for newsletter). The user still has to choose between student and educator options and everything else in the flow is the same.

The only reason we had decide to make Unified flow much shorter and different is because it was supposed to be in a modal IN the context of rex itself. Now that it is in its own link, there is no need  to design and develop (and therefore do more QA) anything different than what we have in OS flow.

**Comment by victoria-cooke** [comment]
@snm8 There's still more to build out on this prototype, but this should cover all of the functions discussed in the doc. I plan to start working on the edit email flow after I get the mobile screens out of the way.

https://t48ysq.axshare.com/#c=2

**Comment by victoria-cooke** [comment]
Spoke with @allisonhowell @snm8 @andymuddimer and @meeragovindaraju yesterday. Decided to go with the edit email flow in place of the alternate email flow because of testing feedback. I'm working on updating the prototype with the necessary changes. Suhani has built draft 3 of the script; I'm finishing up those new interactions as well as the checklist from Next Steps in the doc. Will work on mobile and email screens once the other items are complete.
