### ISSUE TITLE
Apply blog/news page styling to general pages

### ISSUE THREAD

**Issue by allisonhowell** [openstax/business-intel#521]
# Description
The general pages on openstax.org need just a bit more styling to look professional and complete. I suggest applying the styling we have on the blog pages or the press pages
# Acceptance Criteria
- The general pages in the CMS have the basic styling of a blog page or press page. 
# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
There are style changes that have been made to the general pages. There will probably be more changes along the way. But the code (not user facing) does show style changes in Staging.

**Comment by allisonhowell** [comment]
@RoyEJohnson Can we just left-align the documents and videos? (See screenshot)![Screen Shot 2019-09-10 at 12.17.47 PM.png](https://images.zenhubusercontent.com/5bb23bde7a37e50564c6bd7b/72c4a3d4-cd9f-417c-adcd-dce20166596a)

**Comment by allisonhowell** [comment]
@mwharrison The page also needs to accept a header image, just like on the blog pages. Do you want that to be a separate card?

**Comment by mwharrison** [comment]
Yes, please, @allisonhowell

**Comment by RoyEJohnson** [comment]
@allisonhowell I've moved this to Ready for UX Review, but it's probably appropriate for you to do the review. It is included in the release candidate, so should be on QA.

**Comment by allisonhowell** [comment]
@RoyEJohnson Looks good.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
