### ISSUE TITLE
Fall Advocacy Campaign, updating Salesforce data entry processes and procedures

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/business-intel#525]
Hello!

We're starting to prepare for our Fall 2019 advocacy campaign!

This will be the first time that our external sales team will be working in Lightning. Can you please review and update any of the documentation in Appendix A (starts on page 17) of this document so that they have it? https://docs.google.com/document/d/1kNEbYA3hD-hTMZYxzdPwvdfzkqK0DKWdfZTqUdgJAO4/edit?usp=sharing

If we have this information someplace else, can we copy and paste it into this document? To maximize their time and minimize confusion, I try to have every piece of info the sales reps need in this one document.

No rush on this, perhaps by August 15?

Thank you so much for your help! I'll be in touch soon about scheduling their training, updating reports in Salesforce, etc.

Nicole

**Comment by denvergreene** [comment]
@nicolefinkbeiner Completed. It was pretty minor in the documentation. When they're training the biggest difference is where you go to look at things
