### ISSUE TITLE
Implement Edition Redirects without the /books/ in the URL

### ISSUE THREAD

**Issue by openstaxalina** [openstax/business-intel#527]
# Description

When we released redirects from new to old editions, it looks like for some, the following schema was missed:

`https://openstax.org/details/[book-name]`
(Note that this schema is used in the Sample Syllabus language document that we give instructors.)

For example, Dennis reported that http://www.openstax.org/details/american-government 404s rather than redirecting to http://www.openstax.org/details/american-government-2e (thread here https://openstax.slack.com/archives/C0F5B5QEL/p1564161322039800?thread_ts=1564160368.035800&cid=C0F5B5QEL)

We may want to test this for all second editions. https://openstax.org/details/[book-name]

# Acceptance Criteria
- when a user enters https://openstax.org/details/[book-name], if the book is a retired edition, the user is redirected to the latest edition.

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by mwharrison** [comment]
@RoyEJohnson, is this something you can do or is it a devops task?

**Comment by RoyEJohnson** [comment]
> @RoyEJohnson, is this something you can do or is it a devops task?

This is a devops thing.

**Comment by allisonhowell** [comment]
@mwharrison Is this the card you wanted to move to devops?

**Comment by mwharrison** [comment]
@allisonhowell - yes, I think I did that this morning?

**Comment by mwharrison** [comment]
nevermind, I see my mistake :)

**Comment by mwharrison** [comment]
Issue moved to [openstax/devops #203](https://github.com/openstax/devops/issues/203) via [**ZenHub**](https://www.zenhub.com/)
