### ISSUE TITLE
Errata Details Lose Formatting

### ISSUE THREAD

**Issue by openstaxalina** [openstax/business-intel#575]
# Description

When completing the errata submission form, the user often includes more than one paragraph of text.  While the details show as multiple paragraphs as the user is inputting the details, all of this formatting is lost upon submission and all the paragraphs jumble together.

(See screenshots below.)

## Testing
In dev, a good example is https://cms-dev.openstax.org/errata/3847

**SCENARIO** _Briefly describe the issue._

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [x] ` Student  ` [x] ` Teacher
` [ ] ` N/A
- **Username:** any
- **URL:**  any errata form with multiple line breaks/paragraphs
- **Course number:**  N/A
- **Course type:**  N/A

- **Steps**

1) Create an errata submission.  
2) Use the "Enter" key on your keyboard to create new paragraph(s)
3) Notice that you can see the paragraphs on the form as you write the report
4) Notice that once the report is created and submitted, you can no longer see the line breaks/paragraphs -- everything is inline.

----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  Version 76.0.3809.100 (Official Build) (64-bit)

----------------
**Possible impact on a User:**

Difficult to parse errata list.  If effort is spent on separating issues by paragraph or anything like that, this effort is lost.

----------------
**Images or Screenshots** (_attach below_)

![ErrataCMS](https://user-images.githubusercontent.com/7863733/63383103-cbcd8a80-c361-11e9-9aee-3f9b17c40124.png)

![ErrataUserFacing](https://user-images.githubusercontent.com/7863733/63383109-cff9a800-c361-11e9-8d80-52af001472fb.png)

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A high-level solution (development approach for the code change) is added to the issue
- [ ] If prototype code is generated, it is linked to the issue.
- [ ] If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ] Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ] The original issue is changed to an epic and the child story issues are linked to it.  The estimate is removed.
- [ ] The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ] If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ] Distilled acceptance tests are added to the issue.
- [ ] Automated testing criteria are added to issue.
- [ ] The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ] The acceptance tests are finalized in "Given / When / Then" format.
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ] Milestone should be tagged for PR's 
- [ ] Milestone should be tagged for issues
- [ ] Content update needed
- [ ] Content update complete

**Deployment needs**
- [ ] Pre-deployment tasks
- [ ] Data migrations 
- [ ] Post-deployment tasks

_If this issue becomes an epic, delete from 1C-DESIGN to here; otherwise, delete from here to the end_

TRACK / EPICS
- [ ] All child issues are moved to 3B-RELEASE REVIEW.

3B-RELEASE REVIEW
- [ ] Acceptance tests pass for all issues in the release
- [ ] Blessing from Product Manager that the release is good to go.

3C-RELEASED
- [ ] Production is updated and verified.
- [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
