### ISSUE TITLE
Add OpenStax Tutor as Source Option for AP Bio, AP Physics

### ISSUE THREAD

**Issue by openstaxalina** [openstax/business-intel#577]
@openstaxalina commented on [Tue Aug 20 2019](https://github.com/openstax/content-managers/issues/1050)

### Description

Now that we are piloting AP Bio and AP Physics in Tutor, this should appear under the Source options on the errata form.

As an example, it shows for Bio 2e: https://openstax.org/errata/form?book=Biology%202e 

It doesn't currently (but should) show for AP Bio and AP Physics: https://openstax.org/errata/form?book=Biology%20for%20AP%C2%AE%20Courses

----------------
**Information About Change** 

- **Book:** AP Bio, AP Physics
-**Chapter/Section:** N/A
- **CNX URL:** N/A
- **Format:**  
` [ ]` webview ` [ ]` iBook ` [ ]` ancillary
` [ ]` Kindle ` [x]` Wagtail/OpenStax.org ` [ ]` other 
-**Is this for an external partner?**
`[ ]` yes `[x]` no

----------------
**When do you need this by?**
School starts August 26; is it possible to do before to close to then?  I'm not sure what the process is.

---

@yblock commented on [Wed Aug 21 2019](https://github.com/openstax/content-managers/issues/1050#issuecomment-523446424)

@openstaxalina This would be a change to the customer-facing side of openstax.org. I believe I am only to be working on the errata admin page behind the curtain. (tutor is already there as an option in errata admin.)

**Comment by allisonhowell** [comment]
@openstaxalina @lwtchu This is done.
