### ISSUE TITLE
Adjust "Access learning resources" language on Student Getting Started Guide

### ISSUE THREAD

**Issue by openstaxalina** [openstax/business-intel#585]
# Description

The **Access learning resources** language on the Student Getting Started Guide seems to be outdated:

![Screen Shot 2019-08-22 at 3 39 09 PM](https://user-images.githubusercontent.com/7863733/63548124-3c57e100-c4f3-11e9-9f49-ecd3f71a2093.png)

Example: https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/openstax_getting_started_guide_student.pdf

Suggest revising to: 
"If your professor has assigned any additional resources from our partners, find them on your book page by clicking "Partner resources".  Find additional resources, like..." (no change to the second sentence) 

# Acceptance Criteria

The language under **Access learning resources**  has been saved to the Student Getting Started Guide template, and this new document has been uploaded to all book pages (CMs can help with the uploading!)

# Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] High-level natural language acceptance tests are complete
- [ ] If the issue is included in a product phase, then Release is selected.

2A-NON CODE
- [ ] The work is completed and satisfies the acceptance tests.

**Comment by allisonhowell** [comment]
Good catch @openstaxalina! This has been fixed.
