### ISSUE TITLE
Missing two logos on IP website

### ISSUE THREAD

**Issue by nicolefinkbeiner** [openstax/business-intel#663]
There are two institutional partner schools who are missing from our website.

Muskegon Community College is in this year's cohort. Their logo is here: https://drive.google.com/open?id=1fcOHqXPnMNLGaIIqRnbtfLR0xXR362I1

UMass Amherst was previously in a cohort. Here is where you can download their logo. Tier One short wordmark is the correct mark to use: https://www.umass.edu/brand/brand-elements/wordmarks-seal-and-spirit-marks

Can you please let me know when this is done?

Thank you so much!
Nicole

**Comment by allisonhowell** [comment]
@nicolefinkbeiner These have been fixed!
