### ISSUE TITLE
Create ability to manipulate size of in-line blog images

### ISSUE THREAD

**Issue by meeragovindaraju** [openstax/business-intel#72]
### Description
Currently, when you upload an image within a blog post, it takes up the full width of the screen - which sometimes means the image is huge (see screenshot example). It would be helpful to have the ability to choose a smaller version of the image when uploaded (e.g. half width, quarter width).

### Acceptance
When you upload an inline image to a blog post, you are given the option to display the image at smaller sizes.
The image correctly displays in the published blog post at the selected size.
The resized image still works with responsive design.
Impact
Severity: [ ] High [x] Medium [ ] Low

![image.png](https://images.zenhubusercontent.com/5b9c2a1115912b2ee068c7e3/00b970e6-2ca5-421c-836f-898fe131117c)

### Checklist for Done

1A-DEFINE
- [ ] Description is complete
- [ ]  High-level natural language acceptance tests are complete
- [ ]  If UX design is needed then the UX label is added
- [ ]  If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ]  A high-level solution (development approach for the code change) is added to the issue
- [ ]  If prototype code is generated, it is linked to the issue.
- [ ]  If tech briefs are generated, they are linked to the issue.

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items.
- [ ]  Story issues are created for the work items, with Description, Acceptance, the label 'story', and an Estimate.
- [ ]  The original issue is changed to an epic and the child story issues are linked to it. The estimate is removed.
- [ ]  The story epic and child work item issues are moved into 1B-DECOMP DONE.
- [ ]  If an issue is included in a product phase, then Release is selected.

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue.
- [ ]  Distilled acceptance tests are added to the issue.
- [ ]  Automated testing criteria are added to issue.
- [ ]  The solution is updated.

2-CODE
- [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
- [ ]  The acceptance tests are finalized in "Given / When / Then" format.
- [ ]  Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.

4A-UX REVIEW
- [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
- [ ]  Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
- [ ] Production is updated and verified.
- [ ]  All issues in the release are closed.

**QA needs checklist:**
- [ ] Acceptance Criteria are complete
- [ ]  Milestone should be tagged for PR's
- [ ]  Milestone should be tagged for issues
- [ ]  Content update needed
- [ ]  Content update complete

**Deployment needs**
- [ ]  Pre-deployment tasks
- [ ]  Data migrations
- [ ]  Post-deployment tasks

**Comment by meeragovindaraju** [comment]
https://trello.com/c/YAu8hWT4/730-create-ability-to-manipulate-size-of-in-line-blog-images

**Comment by mwharrison** [comment]
@RoyEJohnson - the ability for editors to select the width of the image is already part of the CMS. Is it possible to use this value to set the width of the image on the FE?

```
{
            "type": "aligned_image",
            "id": "8f241c6f-2b16-4c62-a32b-bf6ab6212b6b",
            "value": {
                "alignment": "full",
                "image": 143,
                "alt_text": null,
                "caption": "<p>OpenStax has published 25 textbooks since 2012. (Infographic by Jemel Agulto, OpenStax)</p>"
            }
        },
```

The options for `"alignment"` can be `full` (full width), `mid` (mid width), `right` (wrap right), and `left` (wrap left).

**Comment by RoyEJohnson** [comment]
@mwharrison I don't think the acceptance criteria are clear enough to know whether we can use alignment to solve the problem. We may need some UX input or maybe some more specifications from Courtney (who put the screenshot in the original Trello card). We need to know all the cases and how to handle them.

**Comment by victoria-cooke** [comment]
@mwharrison @RoyEJohnson I'll be getting clarification on this from Courtney tomorrow and will follow up with you once I know more.

**Comment by CourtneyRay** [comment]
@victoria-cooke sample post: https://openstax.org/blog/creator-fests-suzanne-fergus-making-learning-meaningful-connecting-it-real-life

**Comment by victoria-cooke** [comment]
@mwharrison @RoyEJohnson  After speaking with Courtney, it sounds like it's just a matter of providing a few options for the image `max-width` in the CMS. So one full-width option (which is the default now) along with maybe a 3/4 and 1/2 size. That way, the images can be sized down to something like this:

![Screen Shot 2019-06-13 at 2.35.21 PM.png](https://images.zenhubusercontent.com/5c0fedb9d1fab72f0d70aeaa/d6a7b8c7-3c45-4f50-a5ae-abb58e6867af)

**Comment by victoria-cooke** [comment]
@mwharrison @RoyEJohnson I followed up with Courtney. It looks like it's just a matter of providing a few options for the `max-width` of the images being posted. So one full-width option (which is the default now) along with maybe a 3/4 and 1/2 size.

After speaking with Roy, it sounds like he's good to go with everything posted, so I'm assuming this can be implemented. Please let me know if you need anything else from me.

**Comment by victoria-cooke** [comment]
@meeragovindaraju Points updated

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
